# yaml file can't contain Korean. if to do, use UTF-8 encoding everywhere
# you should write mongoDB settings Since Boot 2.7.5... match with version used in project
spring:
  mongodb:
    embedded:
      version: 3.4.11