# Boot 2.7.5 이후로 mongoDB 설정을 project version 에 맞게 적어줘야한다.
spring:
  mongodb:
    embedded:
      version: 3.4.11

# oauth 용 client 인증정보 추가
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: password